# **Titanic Dataset Analysis**

This project involves analyzing the Titanic dataset using Python and pandas. The goal is to explore, clean, and visualize the data, followed by feature engineering and model evaluation.

**Setup and Libraries**

Before we begin, ensure all necessary libraries are imported. If you’re using Google Colab, the following cells guide you through mounting your Google Drive and installing any required packages.

In [ ]:
import pandas as pd

In [ ]:
'''
Linking google colab to the drive folder
'''
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [ ]:
'''
Place the csv files inside your drive and then run this cell
'''
%cd /content/gdrive/My\ Drive/

/content/gdrive/My Drive/DSredo/Assignment1/Part1

# **Data Import and Overview**


We start by importing the dataset and taking an initial look at its structure.

In [ ]:
df=pd.read_csv('top_50_restaurants.csv')
df

A1_1.ipynb  top_50_restaurants.csv

,Year,Ranking,Name,City,Country,Latitude,Longitude
0,2018,1,Osteria Francescana,Modena,Italy,44.643100,10.934100
1,2018,2,El Celler de Can Roca,Girona,Spain,41.980800,2.818700
2,2018,3,Mirazur,Menton,France,43.774700,7.504600
3,2018,4,Eleven Madison Park,New York,USA,40.714600,-74.007100
4,2018,5,Gaggan,Bangkok,Thailand,13.750000,100.516000
5,2018,6,Central,Lima,Peru,-12.043000,-77.028000
6,2018,7,Maido,Lima,Peru,-12.043000,-77.028000
7,2018,8,Arpège,Paris,France,48.856900,2.341200
8,2018,9,Mugaritz,San Sebastian,Spain,43.317400,-1.978400
9,2018,10,Asador Etxebarri,Axpe,Spain,43.130000,-2.583611
10,2018,11,Quintonil,Mexico City,Mexico,19.428500,-99.127700
11,2018,12,Blue Hill at Stone Barns,Pocantico Hills,USA,41.094444,-73.835833
12,2018,13,Pujol,Mexico City,Mexico,19.428500,-99.127700
13,2018,14,Steirereck,Vienna,Austria,48.202500,16.368800
14,2018,15,White Rabbit,Moscow,Russia,55.752000,37.615000
15,2018,16,Piazza Duomo,Alba,Italy,44.696100,8.034100
16,2018,17,Den,Tokyo,Japan,35.624900,139.585600
17,2018,18,Disfrutar,Barcelona,Spain,41.387500,2.168400
18,2018,19,Geranium,Copenhagen,Denmark,55.675000,12.565000
19,2018,20,Attica,Melbourne,Australia,-37.814000,144.963000
20,2018,21,Alain Ducasse au Plaza Athénée,Paris,France,48.856900,2.341200
21,2018,22,Narisawa,Tokyo,Japan,35.624900,139.585600
22,2018,23,Le Calandre,Rubano,Italy,45.433333,11.783333
23,2018,24,Ultraviolet by Paul Pairet,Shanghai,China,31.222000,121.458000
24,2018,25,Cosme,New York,USA,40.714600,-74.007100
25,2018,26,Le Bernardin,New York,USA,40.714600,-74.007100
26,2018,27,Boragó,Santiago,Chile,-33.426000,-70.566000
27,2018,28,Odette,Singapore,Singapore,1.289000,103.850000
28,2018,29,Alléno Paris au Pavillon Ledoyen,Paris,France,48.856900,2.341200
29,2018,30,D.O.M.,São Paulo,Brazil,-23.547000,-46.636000
30,2018,31,Arzak,San Sebastian,Spain,43.317400,-1.978400
31,2018,32,Tickets,Barcelona,Spain,41.387500,2.168400
32,2018,33,The Clove Club,London,UK,51.506400,-0.127200
33,2018,34,Alinea,Chicago,USA,41.884300,-87.632400
34,2018,35,Maaemo,Oslo,Norway,59.912000,10.746000
35,2018,36,Reale,Castel di Sangro,Italy,41.783333,14.100000
36,2018,37,Restaurant Tim Raue,Berlin,Germany,52.516100,13.377000
37,2018,38,Lyle's,London,UK,51.506400,-0.127200
38,2018,39,Astrid y Gastón,Lima,Peru,-12.043000,-77.028000
39,2018,40,Septime,Paris,France,48.856900,2.341200
40,2018,41,Nihonryori RyuGin,Tokyo,Japan,35.624900,139.585600
41,2018,42,The Ledbury,London,UK,51.506400,-0.127200
42,2018,43,Azurmendi,Larrabetzu,Spain,43.261944,-2.794722
43,2018,44,Mikla,Istanbul,Turkey,41.013000,28.949000
44,2018,45,Dinner by Heston Blumenthal,London,UK,51.506400,-0.127200
45,2018,46,Saison,San Francisco,USA,37.777100,-122.419600
46,2018,47,Schloss Schauenstein,Fürstenau,Switzerland,46.716667,9.433333
47,2018,48,Hiša Franko,Kobarid,Slovenia,46.246436,13.578006
48,2018,49,Nahm,Bangkok,Thailand,13.750000,100.516000
49,2018,50,The Test Kitchen,Cape Town,South Africa,-33.916000,18.416000

**Exploring the Dataset**

*Viewing Initial Records*

Let’s take a quick look at the first few and last few rows of the dataset.

In [ ]:
df.head()

,Year,Ranking,Name,City,Country,Latitude,Longitude
0,2018,1,Osteria Francescana,Modena,Italy,44.6431,10.9341
1,2018,2,El Celler de Can Roca,Girona,Spain,41.9808,2.8187
2,2018,3,Mirazur,Menton,France,43.7747,7.5046
3,2018,4,Eleven Madison Park,New York,USA,40.7146,-74.0071
4,2018,5,Gaggan,Bangkok,Thailand,13.7500,100.5160

Last five rows:

In [ ]:
df.tail()

,Year,Ranking,Name,City,Country,Latitude,Longitude
45,2018,46,Saison,San Francisco,USA,37.777100,-122.419600
46,2018,47,Schloss Schauenstein,Fürstenau,Switzerland,46.716667,9.433333
47,2018,48,Hiša Franko,Kobarid,Slovenia,46.246436,13.578006
48,2018,49,Nahm,Bangkok,Thailand,13.750000,100.516000
49,2018,50,The Test Kitchen,Cape Town,South Africa,-33.916000,18.416000

**The most popular in the list of top 50 restaurants**

In [ ]:
df['Country'].value_counts().idxmax()

'Spain'

**The most popular in the list of top 50 restaurants**

In [ ]:
df['City'].value_counts().idxmax()

'London'

**Filtering the Dataset**


Restaurants Ranked Between 35 and 40 (Exclusive)

In [ ]:
df.iloc[35:39]

,Year,Ranking,Name,City,Country,Latitude,Longitude
35,2018,36,Reale,Castel di Sangro,Italy,41.783333,14.1000
36,2018,37,Restaurant Tim Raue,Berlin,Germany,52.516100,13.3770
37,2018,38,Lyle's,London,UK,51.506400,-0.1272
38,2018,39,Astrid y Gastón,Lima,Peru,-12.043000,-77.0280

**Printing the dataframe with restaurants ranking 20-30 (inclusive of 20 and 30) in UK, USA and Spain.**

In [ ]:
df_filtered=df[df['Country'].isin(['UK', 'USA', 'Spain'])]
df_filtered[(df_filtered['Ranking']>=20) & (df_filtered['Ranking']<=30)]

    Year  Ranking          Name      City Country  Latitude  Longitude
24  2018       25         Cosme  New York     USA   40.7146   -74.0071
25  2018       26  Le Bernardin  New York     USA   40.7146   -74.0071

**Comparative Analysis**


*Comparing Peru and Japan*

Let's compare if Peru has more restaurants in the list than to Japan.

In [1]:
per=df[df['Country']=='Peru'].count()['Name']
jap =df[df['Country']=='Japan'].count()['Name']

per>jap

NameError: name 'df' is not defined